/pca9685_driver:
  ros__parameters:
    i2c_bus: 7
    i2c_addr: 0x40
    pitch_channel: 0
    yaw_channel: 1
    thruster_channel: 3


    pitch_centre_us: 825
    pitch_span_us: 325        # pitch: 500-1150us
    yaw_centre_us: 825       
    yaw_span_us: 200          

    fin_max_rad: 0.5
    pitch_sign: 1             # positive fin_pitch -> higher us -> nose up
    yaw_sign: 1               # positive fin_yaw -> higher us -> nose left

    thruster_stop_us: 1480    
    thruster_span_us: 200     # gentle for bench; 400 = full range in water